#
# GitHub Actions workflow configuration.
#
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
#

name: Source
on:
  workflow_call:
defaults:
  run:
    shell: nix develop --command bash -e {0}
jobs:
  multi-storage-client:
    name: multi-storage-client
    strategy:
      matrix:
        python-binary:
          - python3.9
          - python3.10
          - python3.11
          - python3.12
          - python3.13
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop '.#"${{ matrix.python-binary }}"' --command bash -e {0}
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v6
      - working-directory: ./multi-storage-client
        run: |
          just python-binary=${{ matrix.python-binary }} build
          just python-binary=${{ matrix.python-binary }} run-minimal-verification
  multi-storage-client-docs:
    name: multi-storage-client-docs
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v6
      - working-directory: ./multi-storage-client-docs
        run: |
          just build
  multi-storage-explorer:
    name: multi-storage-explorer
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v4
      - working-directory: ./multi-storage-explorer
        run: |
          just build
